#!/bin/bash
#使用脚本需安装CPU频率设置工具： apt install cpufrequtils
#最大评率可以设置为0.7-3.8
#cpu调节器可以设置‘powersave’或‘performance’
  
maxfreq='3.8GHz'
gov='powersave'

for ((i=0;i<$(nproc);i++)); do
    cpufreq-set -g $gov -u $maxfreq -c$i 
done
